#!/usr/bin/env bash
#
# Stops the running 4-to_infinity_and_beyond process using kill command

# shellcheck disable=SC2009
pid=$(ps aux | grep '[4]-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

if [[ -n "$pid" ]]; then
  kill "$pid"
fi
