#!/usr/bin/env bash
#
# Kills all processes matching 7-highlander with SIGKILL.

pids=$(pgrep -f "7-highlander")

if [[ -n "$pids" ]]; then
  # Kill each PID individually
  echo "$pids" | xargs -r kill -9
fi
